AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws-sam-nodejs-example

Parameters:
  environment:
    Type: String
    Default: dev
  customDomain:
    Type: String
    Default: foo.example.com
  stageName:
    Type: String
    Default: dev
  certificateARN:
    Type: String
  regionalAPIGateway:
    Type: String
    AllowedValues: ["Yes", "No"]

Conditions:
  CustomDomainRegional: !Equals [!Ref regionalAPIGateway, "Yes"]

Resources:
  helloworld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda/index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 10
      Events:
        Get:
          Type: Api
          Properties:
            Method: GET
            Path: /helloworld
  APIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ServerlessRestApi.Deployment
      RestApiId: !Ref ServerlessRestApi
      StageName: !Ref stageName

  PathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: ServerlessRestApi
    DependsOn: APIStage
    Properties:
      BasePath: test
      DomainName: !Ref customDomain
      RestApiId: !Ref ServerlessRestApi
      Stage: !Ref APIStage

  APIGCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !If [CustomDomainRegional, !Ref "AWS::NoValue", !Ref certificateARN]
      RegionalCertificateArn: !If [CustomDomainRegional, !Ref certificateARN, !Ref "AWS::NoValue"]
      EndpointConfiguration: 
        Types: 
          - !If [CustomDomainRegional, "REGIONAL", "EDGE"]
      DomainName: !Ref customDomain
    
  